spring:
  common:
    validation:
      msg-locale: zh_CN
    serialization:
      longToString: true
  profiles:
    include: sharding
swagger:
  docket:
    base-package: io.wilson.sharding.controller
mybatis-plus:
  configuration:
    default-scripting-language: io.wilson.sharding.mybatis.ExtMybatisXMLLanguageDriver