swagger:
  docket:
    base-package: io.web.simple

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  common:
    validation:
      msg-locale: cn
    serialization:
      longToString: true