version: "3.7"
services:
  db:
    image: mysql:5.7.28
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: tiger