version: '3'
services:
  web:
    build: ./
    container_name: docker-spring-boot
    image: docker-spring-boot/latest
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /var/lib/docker/volumes/docker-spring-boot:/app
