version: '3'
services:
  app:
    restart: always
    build: ./
    hostname: docker-spring-boot
    container_name: docker-spring-boot
    image: docker-spring-boot/latest
    ports:
      - 8080:8080
    volumes:
      - ./volume:/app
  nginx:
    depends_on:
      - app
    container_name: docker-nginx
    hostname: docker-nginx
    image: nginx:1.17.6
    environment:
      TZ=Asia/Shanghai
    command: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    restart: always
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./nginx:/etc