spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db1:
      url: jdbc:mysql://localhost:3306/wilson?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      user: root
      password: tiger
    db2:
      url: jdbc:mysql://localhost:3306/order_module?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      user: root
      password: tiger
