swagger:
  docket:
    base-package: io.github.validation
    global-parameters:
      - name: token
        param-type: header
        description: 用户token
      - name: appId
        param-type: header
  enabled: true
web:
  common:
    validation:
      msg-locale: zh_CN
